### ISSUE TITLE
ReplayGain cannot be enabled

### ISSUE THREAD

**Issue by Silun** [victoralvesf/aonsoku#148]
When I connected to my Navidrome (v0.54.5 (287079a9)) via https://aonsoku.vercel.app/ it was initially possible to enable ReplayGain in the settings of Aonsoku. A few minutes later, it became greyed out, like so:

![Image](https://github.com/user-attachments/assets/fd62f08f-04f6-4055-a7db-aec4f9235b79)

![Image](https://github.com/user-attachments/assets/3c634d6e-1195-4a43-9e76-c8605b533c54)

Is this a known issue? Anything I can do about this? I tested it and ReplayGain works fine within Navidrome itself, but it is definitely not working in Aonsoku.

**Comment by victoralvesf** [comment]
This happens when the audio is unable to load due to CORS or other network issues. To use Replay Gain, the app needs to request the audio using cross-origin.

After the error occurs, the Replay Gain feature is disabled to avoid interrupting the listening experience.

If you think this is a false positive, just log out and log in again; the toggle will be able to activate.

However, if this continues to happen, you need to check your server.

**Comment by Silun** [comment]
I use caddy and this is the Navidrome entry in my caddyfile:

```
navidrome.domain {

        @cors_preflight {
                method OPTIONS
        }

        respond @cors_preflight 204

        header {
                Access-Control-Allow-Headers *
                Access-Control-Allow-Methods *
                Access-Control-Allow-Origin *
                defer
        }

        reverse_proxy 172.18.0.7:4533 {
                header_down -Access-Control-Allow-Origin
        }
}
```

Since I use caddy-docker-proxy, which works via applying labels to containers, that translates to:

```
    labels:
      caddy: navidrome.domain
      caddy.1_@cors_preflight.method: "OPTIONS"
      caddy.2_respond: "@cors_preflight 204"
      caddy.header.Access-Control-Allow-Origin: "*"
      caddy.header.Access-Control-Allow-Methods: "*"
      caddy.header.Access-Control-Allow-Headers: "*"
      caddy.header.defer:
      caddy.reverse_proxy: "{{upstreams 4533}}"
      caddy.reverse_proxy.header_down: "-Access-Control-Allow-Origin" # Lest Caddy sends this one twice
```

I suppose I could trim the methods, headers, origin a little bit to allow just what Aonsoku needs if that was detailed somewhere, but it works for the moment.
